using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using SUPOptimizer.Core.Logging;

namespace SUPOptimizer.Core.System
{
    public class StorageTarget
    {
        public string Id { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Path { get; set; } = string.Empty;
        public long SizeMb { get; set; }
        public int FileCount { get; set; }
        public bool SafeToClean { get; set; } = true;
    }

    public static class StorageService
    {
        [StructLayout(LayoutKind.Sequential, Pack = 4)]
        private struct SHQUERYRBINFO
        {
            public int cbSize;
            public long i64Size;
            public long i64NumItems;
        }

        [DllImport("Shell32.dll", CharSet = CharSet.Unicode)]
        private static extern int SHQueryRecycleBin(string? pszRootPath, ref SHQUERYRBINFO pSHQueryRBInfo);

        [DllImport("Shell32.dll", CharSet = CharSet.Unicode)]
        private static extern uint SHEmptyRecycleBin(IntPtr hwnd, string? pszRootPath, uint dwFlags);

        private const uint SHERB_NOCONFIRMATION = 0x00000001;
        private const uint SHERB_NOPROGRESSUI = 0x00000002;
        private const uint SHERB_NOSOUND = 0x00000004;

        public static List<StorageTarget> Analyze()
        {
            var targets = new List<StorageTarget>();
            string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            string winDir = Environment.GetFolderPath(Environment.SpecialFolder.Windows);
            string commonAppData = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);

            // 1. Recycle Bin (Accurate measurement across all ready drives)
            var rbStats = QueryRecycleBinStats();
            targets.Add(new StorageTarget
            {
                Id = "recycle_bin",
                Name = "Windows Recycle Bin",
                Description = "Deleted files and folders pending permanent removal across all mounted drives.",
                Path = "Recycle Bin",
                SizeMb = rbStats.SizeMb,
                FileCount = rbStats.ItemCount,
                SafeToClean = true
            });

            // 2. User Temp
            string userTemp = Path.GetTempPath();
            targets.Add(InspectFolder("user_temp", "User Temporary Files", "Temporary files and cache generated by user session applications.", userTemp));

            // 3. Windows System Temp
            string winTemp = Path.Combine(winDir, "Temp");
            targets.Add(InspectFolder("win_temp", "Windows System Temp", "Temporary files generated by Windows operating system services and installers.", winTemp));

            // 4. Windows Update SoftwareDistribution Download Cache
            string winUpdateDownload = Path.Combine(winDir, @"SoftwareDistribution\Download");
            targets.Add(InspectFolder("win_update_cache", "Windows Update Download Cache", "Cumulative update packages and downloaded installation archives.", winUpdateDownload));

            // 5. DirectX / Shader Cache (GPU)
            string d3dCache = Path.Combine(localAppData, "D3DSCache");
            string nvCache = Path.Combine(localAppData, @"NVIDIA\DXCache");
            string amdCache = Path.Combine(localAppData, @"AMD\DxCache");
            targets.Add(InspectMultipleFolders("shader_cache", "DirectX / GPU Shader Cache", "Compiled graphic shader caches for games and multimedia (DirectX, Vulkan, NVIDIA, AMD).", new[] { d3dCache, nvCache, amdCache }));

            // 6. Thumbnail Cache
            string thumbCache = Path.Combine(localAppData, @"Microsoft\Windows\Explorer");
            targets.Add(InspectFiles("thumb_cache", "File Explorer Thumbnail Cache", "Cached image and folder preview thumbnail databases (thumbcache_*.db).", thumbCache, "thumbcache_*.db"));

            // 7. Delivery Optimization
            string deliveryOpt = Path.Combine(winDir, @"SoftwareDistribution\DeliveryOptimization");
            targets.Add(InspectFolder("delivery_opt", "Delivery Optimization Cache", "Peer-to-peer network update delivery cache and downloaded components.", deliveryOpt));

            // 8. Crash Dumps & Minidumps
            string crashDumps = Path.Combine(localAppData, "CrashDumps");
            string winMinidump = Path.Combine(winDir, "Minidump");
            targets.Add(InspectMultipleFolders("crash_dumps", "System & Application Crash Dumps", "Memory dump logs (.dmp) created by process crashes and system bugchecks.", new[] { crashDumps, winMinidump }));

            // 9. Windows Log Files
            string winLogs = Path.Combine(winDir, "Logs");
            string pantherLogs = Path.Combine(winDir, "Panther");
            targets.Add(InspectMultipleFolders("win_logs", "System & Setup Log Files", "Historical event logs from Windows installations, servicing, and component updates.", new[] { winLogs, pantherLogs }));

            // 10. Google Chrome Web Cache
            string chromeCache = Path.Combine(localAppData, @"Google\Chrome\User Data\Default\Cache");
            targets.Add(InspectFolder("chrome_cache", "Google Chrome Web Cache", "Cached web media, images, and scripts from Chrome browsing sessions.", chromeCache));

            // 11. Microsoft Edge Web Cache
            string edgeCache = Path.Combine(localAppData, @"Microsoft\Edge\User Data\Default\Cache");
            targets.Add(InspectFolder("edge_cache", "Microsoft Edge Web Cache", "Cached temporary internet files and offline web assets from Edge.", edgeCache));

            // 12. Windows Error Reporting Archive
            string werArchive = Path.Combine(commonAppData, @"Microsoft\Windows\WER\ReportArchive");
            string werQueue = Path.Combine(commonAppData, @"Microsoft\Windows\WER\ReportQueue");
            targets.Add(InspectMultipleFolders("wer_reports", "Windows Error Reporting (WER)", "Diagnostic reports and telemetry archives queued for transmission.", new[] { werArchive, werQueue }));

            return targets;
        }

        private static (long SizeMb, int ItemCount) QueryRecycleBinStats()
        {
            long totalBytes = 0;
            long totalItems = 0;

            try
            {
                // Query system-wide via null root path
                var rbInfo = new SHQUERYRBINFO { cbSize = Marshal.SizeOf(typeof(SHQUERYRBINFO)) };
                int hr = SHQueryRecycleBin(null, ref rbInfo);
                if (hr == 0 && (rbInfo.i64NumItems > 0 || rbInfo.i64Size > 0))
                {
                    totalBytes = rbInfo.i64Size;
                    totalItems = rbInfo.i64NumItems;
                }
                else
                {
                    // Query each ready drive individually
                    foreach (var drive in DriveInfo.GetDrives())
                    {
                        if (drive.IsReady && (drive.DriveType == DriveType.Fixed || drive.DriveType == DriveType.Removable))
                        {
                            var dInfo = new SHQUERYRBINFO { cbSize = Marshal.SizeOf(typeof(SHQUERYRBINFO)) };
                            if (SHQueryRecycleBin(drive.Name, ref dInfo) == 0)
                            {
                                totalBytes += dInfo.i64Size;
                                totalItems += dInfo.i64NumItems;
                            }
                        }
                    }
                }
            }
            catch { }

            // Fallback: manual scan of $Recycle.Bin directories if API returned 0 but files exist
            if (totalItems == 0)
            {
                try
                {
                    foreach (var drive in DriveInfo.GetDrives())
                    {
                        if (drive.IsReady && drive.DriveType == DriveType.Fixed)
                        {
                            string rbFolder = Path.Combine(drive.Name, "$Recycle.Bin");
                            if (Directory.Exists(rbFolder))
                            {
                                var di = new DirectoryInfo(rbFolder);
                                foreach (var fi in di.EnumerateFiles("*", SearchOption.AllDirectories))
                                {
                                    try
                                    {
                                        totalBytes += fi.Length;
                                        totalItems++;
                                    }
                                    catch { }
                                }
                            }
                        }
                    }
                }
                catch { }
            }

            long mb = totalBytes / (1024 * 1024);
            if (totalBytes > 0 && mb == 0) mb = 1; // Round up small bytes to 1 MB

            return (mb, (int)totalItems);
        }

        private static StorageTarget InspectFolder(string id, string name, string desc, string folderPath)
        {
            long size = 0;
            int count = 0;

            if (Directory.Exists(folderPath))
            {
                try
                {
                    var di = new DirectoryInfo(folderPath);
                    foreach (var fi in di.EnumerateFiles("*", SearchOption.AllDirectories))
                    {
                        try
                        {
                            size += fi.Length;
                            count++;
                        }
                        catch { }
                    }
                }
                catch { }
            }

            return new StorageTarget
            {
                Id = id,
                Name = name,
                Description = desc,
                Path = folderPath,
                SizeMb = size / (1024 * 1024),
                FileCount = count,
                SafeToClean = true
            };
        }

        private static StorageTarget InspectMultipleFolders(string id, string name, string desc, string[] folders)
        {
            long size = 0;
            int count = 0;

            foreach (var folder in folders)
            {
                if (Directory.Exists(folder))
                {
                    try
                    {
                        var di = new DirectoryInfo(folder);
                        foreach (var fi in di.EnumerateFiles("*", SearchOption.AllDirectories))
                        {
                            try
                            {
                                size += fi.Length;
                                count++;
                            }
                            catch { }
                        }
                    }
                    catch { }
                }
            }

            return new StorageTarget
            {
                Id = id,
                Name = name,
                Description = desc,
                Path = string.Join(" ; ", folders),
                SizeMb = size / (1024 * 1024),
                FileCount = count,
                SafeToClean = true
            };
        }

        private static StorageTarget InspectFiles(string id, string name, string desc, string folderPath, string pattern)
        {
            long size = 0;
            int count = 0;

            if (Directory.Exists(folderPath))
            {
                try
                {
                    var di = new DirectoryInfo(folderPath);
                    foreach (var fi in di.EnumerateFiles(pattern, SearchOption.TopDirectoryOnly))
                    {
                        try
                        {
                            size += fi.Length;
                            count++;
                        }
                        catch { }
                    }
                }
                catch { }
            }

            return new StorageTarget
            {
                Id = id,
                Name = name,
                Description = desc,
                Path = folderPath,
                SizeMb = size / (1024 * 1024),
                FileCount = count,
                SafeToClean = true
            };
        }

        public static (bool Success, string Message, long CleanedMb) Clean(List<string> targetIds, bool dryRun)
        {
            long totalCleanedBytes = 0;
            int totalDeletedFiles = 0;

            if (dryRun)
            {
                var analysis = Analyze();
                long previewMb = 0;
                foreach (var item in analysis)
                {
                    if (targetIds.Contains(item.Id))
                        previewMb += item.SizeMb;
                }
                return (true, $"[PREVIEW] Pulizia simulata: liberati fino a {previewMb} MB.", previewMb);
            }

            string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            string winDir = Environment.GetFolderPath(Environment.SpecialFolder.Windows);
            string commonAppData = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);

            foreach (var id in targetIds)
            {
                try
                {
                    if (id == "recycle_bin")
                    {
                        var statsBefore = QueryRecycleBinStats();
                        SHEmptyRecycleBin(IntPtr.Zero, null, SHERB_NOCONFIRMATION | SHERB_NOPROGRESSUI | SHERB_NOSOUND);
                        totalCleanedBytes += statsBefore.SizeMb * 1024 * 1024;
                        totalDeletedFiles += statsBefore.ItemCount;
                        continue;
                    }

                    var foldersToClean = new List<string>();

                    switch (id)
                    {
                        case "user_temp":
                            foldersToClean.Add(Path.GetTempPath());
                            break;
                        case "win_temp":
                            foldersToClean.Add(Path.Combine(winDir, "Temp"));
                            break;
                        case "win_update_cache":
                            foldersToClean.Add(Path.Combine(winDir, @"SoftwareDistribution\Download"));
                            break;
                        case "shader_cache":
                            foldersToClean.Add(Path.Combine(localAppData, "D3DSCache"));
                            foldersToClean.Add(Path.Combine(localAppData, @"NVIDIA\DXCache"));
                            foldersToClean.Add(Path.Combine(localAppData, @"AMD\DxCache"));
                            break;
                        case "delivery_opt":
                            foldersToClean.Add(Path.Combine(winDir, @"SoftwareDistribution\DeliveryOptimization"));
                            break;
                        case "crash_dumps":
                            foldersToClean.Add(Path.Combine(localAppData, "CrashDumps"));
                            foldersToClean.Add(Path.Combine(winDir, "Minidump"));
                            break;
                        case "win_logs":
                            foldersToClean.Add(Path.Combine(winDir, "Logs"));
                            foldersToClean.Add(Path.Combine(winDir, "Panther"));
                            break;
                        case "chrome_cache":
                            foldersToClean.Add(Path.Combine(localAppData, @"Google\Chrome\User Data\Default\Cache"));
                            break;
                        case "edge_cache":
                            foldersToClean.Add(Path.Combine(localAppData, @"Microsoft\Edge\User Data\Default\Cache"));
                            break;
                        case "wer_reports":
                            foldersToClean.Add(Path.Combine(commonAppData, @"Microsoft\Windows\WER\ReportArchive"));
                            foldersToClean.Add(Path.Combine(commonAppData, @"Microsoft\Windows\WER\ReportQueue"));
                            break;
                        case "thumb_cache":
                            string thumbFolder = Path.Combine(localAppData, @"Microsoft\Windows\Explorer");
                            if (Directory.Exists(thumbFolder))
                            {
                                var di = new DirectoryInfo(thumbFolder);
                                foreach (var fi in di.EnumerateFiles("thumbcache_*.db", SearchOption.TopDirectoryOnly))
                                {
                                    try
                                    {
                                        long len = fi.Length;
                                        fi.Delete();
                                        totalCleanedBytes += len;
                                        totalDeletedFiles++;
                                    }
                                    catch { }
                                }
                            }
                            break;
                    }

                    foreach (var folder in foldersToClean)
                    {
                        if (Directory.Exists(folder))
                        {
                            var di = new DirectoryInfo(folder);
                            foreach (var fi in di.EnumerateFiles("*", SearchOption.AllDirectories))
                            {
                                try
                                {
                                    long len = fi.Length;
                                    fi.Delete();
                                    totalCleanedBytes += len;
                                    totalDeletedFiles++;
                                }
                                catch { }
                            }
                        }
                    }
                }
                catch { }
            }

            long cleanedMb = totalCleanedBytes / (1024 * 1024);
            AuditLogger.Log("Storage", "Cleaned Temporary Files", $"Cleaned {cleanedMb} MB ({totalDeletedFiles} files deleted)");
            return (true, $"Disk cleanup completed successfully. Reclaimed {cleanedMb} MB ({totalDeletedFiles} files removed).", cleanedMb);
        }
    }
}
